### ISSUE TITLE
SimpleDemoVerticle  NO_HANDLERS

### ISSUE THREAD

**Issue by plutext** [plutext/neo4vertx#2]
Running SimpleDemoVerticle unchanged, with the deps specified in the pom, results in:

Oct 23, 2015 1:40:28 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
INFO: Starting org.openpcf.neo4vertx.examples.SimpleDemoVerticle
Oct 23, 2015 1:40:29 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
INFO: Started org.openpcf.neo4vertx.examples.SimpleDemoVerticle
Oct 23, 2015 1:40:29 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
INFO: Verticle {class org.openpcf.neo4vertx.examples.SimpleDemoVerticle} deployed
Oct 23, 2015 1:40:29 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
INFO: Neo4Vertx deployed
Oct 23, 2015 1:40:58 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
INFO: Sending query: CREATE (testentry:ingredient1445568058333 {time : '1445568058333'})
Oct 23, 2015 1:40:58 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
INFO: Sending query: MATCH (n) RETURN count(*);
Oct 23, 2015 1:41:59 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
SEVERE: Storing failed
(NO_HANDLERS,-1) 
    at io.vertx.core.eventbus.impl.EventBusImpl.lambda$sendNoHandlersFailure$188(EventBusImpl.java:740)
    at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$18/1245967104.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:314)
    at io.vertx.core.impl.ContextImpl$$Lambda$5/715378067.run(Unknown Source)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at java.lang.Thread.run(Unknown Source)

Oct 23, 2015 1:41:59 PM org.openpcf.neo4vertx.examples.AbstractDemoVerticle
SEVERE: Counting failed
(NO_HANDLERS,-1) 
    at io.vertx.core.eventbus.impl.EventBusImpl.lambda$sendNoHandlersFailure$188(EventBusImpl.java:740)
    at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$18/1245967104.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:314)
    at io.vertx.core.impl.ContextImpl$$Lambda$5/715378067.run(Unknown Source)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at java.lang.Thread.run(Unknown Source)

**Comment by Jotschi** [comment]
I think the master branch version is currently broken. It is mandatory to add the gui-extension in order to be able to send queries and the neo4vertx implementation may need to be adapted.  Using https://github.com/aschrijver/mod-tinkerpop-persistor may be a better alternative. I personally switched to solution where i'm not using the eventbus altogether.
